### ISSUE TITLE
Update for compatibility with Qt Creator 13.0.0 on Windows

### ISSUE THREAD

**Issue by PolymorphicAgent** [eduardoc7/qtcreator-plugin-discord-presence#1]
Please update this to work with Qt Creator 13.0.0
I get the following error when attempting to load it:
`
C:\Qt\Tools\QtCreator\lib\qtcreator\plugins\CuteDiscordPresence.dll: Cannot load library C:\Qt\Tools\QtCreator\lib\qtcreator\plugins\CuteDiscordPresence.dll: The specified module could not be found.
`

**Comment by eduardoc7** [comment]
Hi @pete-the-dev, thank you for your issue. 

I intend to improve the way discord-rpc dependencies are handled and integrate them into releases. However, this is not possible yet.

To solve this issue, you can manually download the dependencies from here https://github.com/discord/discord-rpc/releases and place them in the missing path. You can also refer to this repository release to compare how the dependency paths should look like https://github.com/eduardoc7/qtcreator-plugin-discord-presence/releases/tag/latest

**Comment by PolymorphicAgent** [comment]
I attempted to put `discord-rpc.dll` (from https://github.com/discord/discord-rpc/releases) under `bin/` and the `CuteDiscordPresence.dll` under `lib/qtcreator/plugins/` but I get the following error:

`C:\Qt\Tools\QtCreator\lib\qtcreator\plugins\CuteDiscordPresence.dll: Cannot load library C:\Qt\Tools\QtCreator\lib\qtcreator\plugins\CuteDiscordPresence.dll: The specified procedure could not be found.`

I tried all of the combinations of both the included `discord-rpc.dll` and the file provided from the official github, but none worked saying that the dll was invalid:

`C:\Users\user\AppData\Local\QtProject\qtcreator\plugins\13.0.0\CuteDiscordPresence.dll: Cannot load library C:\Users\user\AppData\Local\QtProject\qtcreator\plugins\13.0.0\CuteDiscordPresence.dll: %1 is not a valid Win32 application.`

I also tried different plugin locations (i.e. under AppData vs under C:/Qt)

not sure what's going on

**Comment by eduardoc7** [comment]
> I attempted to put `discord-rpc.dll` (from https://github.com/discord/discord-rpc/releases) under `bin/` and the `CuteDiscordPresence.dll` under `lib/qtcreator/plugins/` but I get the following error:
> 
> `C:\Qt\Tools\QtCreator\lib\qtcreator\plugins\CuteDiscordPresence.dll: Cannot load library C:\Qt\Tools\QtCreator\lib\qtcreator\plugins\CuteDiscordPresence.dll: The specified procedure could not be found.`
> 
> I tried all of the combinations of both the included `discord-rpc.dll` and the file provided from the official github, but none worked saying that the dll was invalid:
> 
> `C:\Users\user\AppData\Local\QtProject\qtcreator\plugins\13.0.0\CuteDiscordPresence.dll: Cannot load library C:\Users\user\AppData\Local\QtProject\qtcreator\plugins\13.0.0\CuteDiscordPresence.dll: %1 is not a valid Win32 application.`
> 
> I also tried different plugin locations (i.e. under AppData vs under C:/Qt)
> 
> not sure what's going on

**Comment by eduardoc7** [comment]
Sorry for my previous response, I realized later that the issue wasn't with the Discord RPC library and deleted the response.

The problem seems to lie in how the plugin is being generated for Windows; I hadn't tested it for Windows yet, only for Linux. I'll investigate the problem and get back to you.

If you'd like to try a solution, you can clone the repository and build the plugin following the instructions in the readme for your specific platform.

**Comment by PolymorphicAgent** [comment]
Yes, thanks for the effort! I will look into building it.

**Comment by eduardoc7** [comment]
hi @pete-the-dev

After seeing your error, I realized this: "%1 is not a valid Win32 application."

Could you provide more information about the platform you're trying to run Qt Creator 13 and the plugin on? Is your Windows system 32-bit or 64-bit?

I ask this because if you look at the repository releases, you'll see that for Windows, there's only a release for x64.

**Comment by PolymorphicAgent** [comment]
I am running an x64 system. I just attempted to load the x32 `discord-rpc.dll` as a last ditch attempt to get it to work - sorry I didn't mention that earlier.

**Comment by eduardoc7** [comment]
I made some tests using the plugin on Linux Ubuntu 22.04, and it works perfectly. It seems that the issue might be specific to installing the plugin on Windows. Therefore, I have updated the issue title accordingly.

Currently, I am unable to investigate the problem further as I do not use Windows. However, I suspect that the issue may arise from linking the discord-rpc library and your DLL. I believe this can be resolved by making adjustments to the build process and CMake files.

Feel free to explore the problem further, particularly regarding the linking of the discord-rpc library on Windows. I would greatly appreciate it if someone could delve into this matter.

**Comment by PolymorphicAgent** [comment]
I have windows but am not really experienced with compiling qt creator plugins. I will try my best but no promises...

**Comment by eduardoc7** [comment]
The compatibility issue with Windows has been resolved. Indeed, there was an issue with linking the discord-rpc library. 

I also made some improvements, which you can check out in the [commit](https://github.com/eduardoc7/qtcreator-plugin-discord-presence/commit/3b63865ee5516ea04f9cff20f6e00f2d9ced6727). Feel free to use the plugin with the [updated release](https://github.com/eduardoc7/qtcreator-plugin-discord-presence/releases/tag/v0.1.0). Thank you for reporting the issue.

**Comment by PolymorphicAgent** [comment]
wow, thanks! I was getting nowhere with that to be honest...
